# -*- coding: utf-8 -*-
"""Revisando_AGENTE_Gemini.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YEz2mOlW1YlSBee2gAQbAexisbTP0s5y
"""

!pip install streamlit

#Bibliotecas

import streamlit as st
import pandas as pd
import plotly.express as px
import requests
from google import genai

# -----------------------------------------------------------------------------
# 1. CONFIGURAÇÃO DA PÁGINA STREAMLIT
# -----------------------------------------------------------------------------
st.set_page_config(
    page_title="Dashboard IBGE + Agente IA",
    layout="wide"
)

st.title("📊 Dashboard de Notícias do IBGE com Agente de IA")

# -----------------------------------------------------------------------------
# 2. COLETA E TRATAMENTO DOS DADOS (PANDAS + API IBGE)
# -----------------------------------------------------------------------------

def carregar_dados_ibge():
    """Busca dados da API do IBGE e retorna um DataFrame do Pandas limpo."""
    url = "https://servicodados.ibge.gov.br/api/v3/noticias/?qtd=100"

    resposta = requests.get(url)
    dados_json = resposta.json()

    # A API do IBGE retorna as notícias dentro da chave 'items'
    lista_noticias = dados_json.get("items", [])

    df = pd.DataFrame(lista_noticias)

    # Tratamento básico dos dados
    # Selecionando colunas relevantes
    colunas_desejadas = ["id", "titulo", "editorias", "tipo", "data_publicacao"]
    df = df[colunas_desejadas]

    # Convertendo a coluna 'data_publicacao' para formato de data
    df["data_publicacao"] = pd.to_datetime(df["data_publicacao"], format="%d/%m/%Y %H:%M:%S", errors="coerce")

    # Extraindo o ano e mês para facilitar análises
    df["ano_mes"] = df["data_publicacao"].dt.strftime("%Y-%m")

    # Limpando editorias (vem no formato de string contendo tags)
    df["editorias"] = df["editorias"].astype(str).str.replace("[", "").str.replace("]", "").str.replace("'", "")
    df["editorias"] = df["editorias"].fillna("Geral")

    return df

# Carregar o DataFrame
df_noticias = carregar_dados_ibge()

if df_noticias.empty:
    st.warning("Não foi possível carregar os dados. Verifique sua conexão.")
    st.stop()

# -----------------------------------------------------------------------------
# 3. VISUALIZAÇÃO DE DADOS (DASHBOARD PLOTLY)
# -----------------------------------------------------------------------------

# Gráfico 1: Barras - Quantidade de Notícias por Editoria
st.subheader("1. Quantidade de Publicações por Editoria")
df_editorias = df_noticias["editorias"].value_counts().reset_index()
df_editorias.columns = ["Editoria", "Quantidade"]

fig_barras = px.bar(
    df_editorias.head(10),
    x="Editoria",
    y="Quantidade",
    color="Quantidade",
    title="Top 10 Editorias mais Frequentes",
    text_auto=True
)
st.plotly_chart(fig_barras, use_container_width=True)

# Gráfico 2: Pizza - Distribuição por Tipo de Conteúdo
st.subheader("2. Distribuição por Tipo de Conteúdo")
df_tipos = df_noticias["tipo"].value_counts().reset_index()
df_tipos.columns = ["Tipo", "Quantidade"]

fig_pizza = px.pie(
    df_tipos,
    names="Tipo",
    values="Quantidade",
    title="Proporção de Notícias vs Releases",
    hole=0.4
)
st.plotly_chart(fig_pizza, use_container_width=True)

# Gráfico 3: Linha/Área - Publicações ao Longo do Tempo
st.subheader("3. Volume de Publicações por Ano/Mês")
df_tempo = df_noticias.groupby("ano_mes").size().reset_index(name="Quantidade")

fig_linha = px.line(
    df_tempo,
    x="ano_mes",
    y="Quantidade",
    title="Evolução Temporal das Publicações",
    markers=True
)
st.plotly_chart(fig_linha, use_container_width=True)

# -----------------------------------------------------------------------------
# 4. CONFIGURANDO ESPAÇO PARA AGENTE NO DASHBOARD
# -----------------------------------------------------------------------------
st.subheader("🤖 Pergunte ao Agente sobre os Dados")
st.markdown("Digite uma pergunta sobre o conjunto de dados exibido acima.")

# Input para chave API do Google Gemini
api_key = st.text_input("Cole sua Google Gemini API Key para ativar o Agente:", type="password")

pergunta_usuario = st.text_input("Sua pergunta:")

# -----------------------------------------------------------------------------
# 5. AGENTE DE IA (PERGUNTAS E RESPOSTAS)
# -----------------------------------------------------------------------------
def executar_agente_ia(pergunta, df, chave_api):
    """Executa o agente de IA utilizando o Google Gemini com os dados em contexto."""
    if not chave_api:
        return "⚠️ Por favor, informe sua API Key do Google Gemini para continuar."

    genai.configure(api_key=chave_api)
    model = genai.GenerativeModel('gemini-2.5-flash')

    # Resumo estruturado do DataFrame para contexto
    resumo_dados = f"""
    Você é um agente analisador de dados. Responda apenas com base nas informações abaixo.

    RESUMO DO DATAFRAME:
    - Total de registros: {len(df)}
    - Tipos de conteúdo disponíveis: {df['tipo'].value_counts().to_dict()}
    - Principais editorias e contagens: {df['editorias'].value_counts().head(10).to_dict()}
    - Período das publicações: de {df['data_publicacao'].min()} até {df['data_publicacao'].max()}
    - Primeiros 5 títulos da base: {df['titulo'].head(5).tolist()}
    """

    prompt_final = f"""
    {resumo_dados}

    PERGUNTA DO USUÁRIO: {pergunta}

    REGRAS DE RESPOSTA:
    1. Responda de forma clara, direta e objetiva.
    2. Use APENAS os dados fornecidos acima. Se não souber a resposta com base nos dados, diga que não possui essa informação.
    3. Não invente números ou dados fictícios.
    """

    resposta = model.generate_content(prompt_final)
    return resposta.text

# -----------------------------------------------------------------------------
# 6. EXECUTANDO AGENTE DE IA (PERGUNTAS E RESPOSTAS)
# -----------------------------------------------------------------------------
if st.button("Enviar Pergunta"):
    if pergunta_usuario:
        with st.spinner("O Agente está analisando os dados..."):
            resposta_agente = executar_agente_ia(pergunta_usuario, df_noticias, api_key)
            st.success("Resposta do Agente:")
            st.write(resposta_agente)
    else:
        st.warning("Por favor, digite uma pergunta antes de enviar.")